---

- name: Systemctl daemon-reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    force: true
  when:
    - ansible_service_mgr | lower == "systemd"

- name: Validate configuration
  ansible.builtin.command:
    cmd: dnsmasq --test
  register: dnsmasq_test
  changed_when: dnsmasq_test.rc != 0
  failed_when: dnsmasq_test.rc != 0

- name: Restart service
  ansible.builtin.service:
    name: "{{ dnsmasq_service }}"
    state: restarted
  listen: restart dnsmasq
  when: service_default_state | default('started') == 'started'

- name: Reload service
  ansible.builtin.service:
    name: "{{ dnsmasq_service }}"
    state: reloaded
  listen: reload dnsmasq
  when: service_default_state | default('started') == 'started'
