- name: Copy SSL certificate
  copy:
    src: "{{ squid_ssl_bump_cert_path | basename }}"
    dest: "{{ squid_ssl_bump_cert_path }}"
    mode: '0644'
  when: squid_ssl_bump_enabled

- name: Copy SSL key
  copy:
    src: "{{ squid_ssl_bump_key_path | basename }}"
    dest: "{{ squid_ssl_bump_key_path }}"
    mode: '0600'
  when: squid_ssl_bump_enabled

- name: Copy client SSL certificate
  copy:
    src: "{{ squid_ssl_bump_client_cert | basename }}"
    dest: "{{ squid_ssl_bump_client_cert }}"
    mode: '0644'
  when: squid_ssl_bump_enabled

- name: Copy client SSL private key
  copy:
    src: "{{ squid_ssl_bump_client_private_key | basename }}"
    dest: "{{ squid_ssl_bump_client_private_key }}"
    mode: '0600'
  when: squid_ssl_bump_enabled